// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://timlyhwzltplfqbxpwjx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpbWx5aHd6bHRwbGZxYnhwd2p4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MzYwODAsImV4cCI6MjA2NTQxMjA4MH0.syK5_VWsAuzBrbnXNucet6fubsh9qAUMd_dY6P0dT9w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);